"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from dateno.errors import SDKError
from dateno.types import BaseModel
import httpx
from typing import Optional


class ErrorResponseData(BaseModel):
    detail: str


@dataclass(unsafe_hash=True)
class ErrorResponse(SDKError):
    r"""Standard error response payload."""

    data: ErrorResponseData = field(hash=False)

    def __init__(
        self,
        data: ErrorResponseData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
