"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .datacatalogsearchitem import DataCatalogSearchItem, DataCatalogSearchItemTypedDict
from .searchmeta import SearchMeta, SearchMetaTypedDict
from dateno.types import BaseModel
from dateno.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DataCatalogSearchResponseTypedDict(TypedDict):
    r"""Search response for data catalogs."""

    meta: SearchMetaTypedDict
    r"""Pagination metadata for list/search endpoints."""
    source: Literal["api"]
    r"""API version / source identifier"""
    data: NotRequired[List[DataCatalogSearchItemTypedDict]]


class DataCatalogSearchResponse(BaseModel):
    r"""Search response for data catalogs."""

    meta: SearchMeta
    r"""Pagination metadata for list/search endpoints."""

    source: Annotated[
        Annotated[Optional[Literal["api"]], AfterValidator(validate_const("api"))],
        pydantic.Field(alias="source"),
    ] = "api"
    r"""API version / source identifier"""

    data: Optional[List[DataCatalogSearchItem]] = None
