"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .namespace import Namespace, NamespaceTypedDict
from dateno.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class PageNamespaceTypedDict(TypedDict):
    totals: int
    start: int
    limit: int
    items: NotRequired[List[NamespaceTypedDict]]


class PageNamespace(BaseModel):
    totals: int

    start: int

    limit: int

    items: Optional[List[Namespace]] = None
