"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dateno.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


SearchIndexResourceRecordIDTypedDict = TypeAliasType(
    "SearchIndexResourceRecordIDTypedDict", Union[str, int]
)


SearchIndexResourceRecordID = TypeAliasType(
    "SearchIndexResourceRecordID", Union[str, int]
)


DatasizeTypedDict = TypeAliasType("DatasizeTypedDict", Union[str, int])


Datasize = TypeAliasType("Datasize", Union[str, int])


class SearchIndexResourceRecordTypedDict(TypedDict):
    id: NotRequired[Nullable[SearchIndexResourceRecordIDTypedDict]]
    name: NotRequired[Nullable[str]]
    datasize: NotRequired[Nullable[DatasizeTypedDict]]
    format_: NotRequired[Nullable[str]]
    mimetype: NotRequired[Nullable[str]]
    url: NotRequired[Nullable[str]]


class SearchIndexResourceRecord(BaseModel):
    id: OptionalNullable[SearchIndexResourceRecordID] = UNSET

    name: OptionalNullable[str] = UNSET

    datasize: OptionalNullable[Datasize] = UNSET

    format_: Annotated[OptionalNullable[str], pydantic.Field(alias="format")] = UNSET

    mimetype: OptionalNullable[str] = UNSET

    url: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["id", "name", "datasize", "format", "mimetype", "url"]
        nullable_fields = ["id", "name", "datasize", "format", "mimetype", "url"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
