"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .searchindexdatasetrecord import (
    SearchIndexDatasetRecord,
    SearchIndexDatasetRecordTypedDict,
)
from .searchindexresourcerecord import (
    SearchIndexResourceRecord,
    SearchIndexResourceRecordTypedDict,
)
from .searchindexsourcerecord import (
    SearchIndexSourceRecord,
    SearchIndexSourceRecordTypedDict,
)
from dateno.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class SearchIndexEntryTypedDict(TypedDict):
    id: str
    source: SearchIndexSourceRecordTypedDict
    dataset: SearchIndexDatasetRecordTypedDict
    int_id: NotRequired[Nullable[str]]
    resources: NotRequired[List[SearchIndexResourceRecordTypedDict]]


class SearchIndexEntry(BaseModel):
    id: str

    source: SearchIndexSourceRecord

    dataset: SearchIndexDatasetRecord

    int_id: OptionalNullable[str] = UNSET

    resources: Optional[List[SearchIndexResourceRecord]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["int_id", "resources"]
        nullable_fields = ["int_id"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
