"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .fieldspec import FieldSpec, FieldSpecTypedDict
from .metadatafield import MetadataField, MetadataFieldTypedDict
from dateno.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TimeseriesWithSchemaTypedDict(TypedDict):
    r"""Timeseries metadata with schema (and optional metadata)."""

    id: str
    indicator: str
    table: str
    name: str
    metadata: NotRequired[List[MetadataFieldTypedDict]]
    schema_: NotRequired[List[FieldSpecTypedDict]]
    r"""Schema for the underlying table"""


class TimeseriesWithSchema(BaseModel):
    r"""Timeseries metadata with schema (and optional metadata)."""

    id: str

    indicator: str

    table: str

    name: str

    metadata: Optional[List[MetadataField]] = None

    schema_: Annotated[Optional[List[FieldSpec]], pydantic.Field(alias="schema")] = None
    r"""Schema for the underlying table"""
