"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import TYPE_CHECKING
from importlib import import_module
import builtins
import sys

if TYPE_CHECKING:
    from .body_dataset_search_using_elastic_dsl_search_0_2_es_search_post import (
        BodyDatasetSearchUsingElasticDSLSearch02EsSearchPost,
        BodyDatasetSearchUsingElasticDSLSearch02EsSearchPostTypedDict,
    )
    from .country import Country, CountryTypedDict
    from .datacatalog import DataCatalog, DataCatalogTypedDict
    from .datacatalogsearchitem import (
        DataCatalogSearchItem,
        DataCatalogSearchItemTypedDict,
    )
    from .datacatalogsearchresponse import (
        DataCatalogSearchResponse,
        DataCatalogSearchResponseTypedDict,
    )
    from .dataset_search_using_elastic_dsl_search_0_2_es_search_postop import (
        DatasetSearchUsingElasticDSLSearch02EsSearchPostRequest,
        DatasetSearchUsingElasticDSLSearch02EsSearchPostRequestTypedDict,
    )
    from .dimensionspec import DimensionSpec, DimensionSpecTypedDict
    from .endpoint import Endpoint, EndpointTypedDict
    from .export_timeseries_data_statsdb_0_1_ns_ns_id_ts_ts_id_export_fileext_getop import (
        ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetRequest,
        ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetRequestTypedDict,
        ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetResponse,
        ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetResponseResult,
        ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetResponseResultTypedDict,
        ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetResponseTypedDict,
    )
    from .facetinfo import FacetInfo, FacetInfoTypedDict
    from .facetitem import FacetItem, FacetItemTypedDict
    from .facetvaluesresponse import FacetValuesResponse, FacetValuesResponseTypedDict
    from .fieldspec import FieldSpec, FieldSpecTypedDict
    from .get_data_catalog_record_registry_catalog_catalog_id_getop import (
        GetDataCatalogRecordRegistryCatalogCatalogIDGetRequest,
        GetDataCatalogRecordRegistryCatalogCatalogIDGetRequestTypedDict,
    )
    from .get_facet_values_search_0_2_get_facet_getop import (
        GetFacetValuesSearch02GetFacetGetRequest,
        GetFacetValuesSearch02GetFacetGetRequestTypedDict,
    )
    from .get_indicator_metadata_statsdb_0_1_ns_ns_id_indicators_ind_id_getop import (
        GetIndicatorMetadataStatsdb01NsNsIDIndicatorsIndIDGetRequest,
        GetIndicatorMetadataStatsdb01NsNsIDIndicatorsIndIDGetRequestTypedDict,
    )
    from .get_namespace_database_metadata_statsdb_0_1_ns_ns_id_getop import (
        GetNamespaceDatabaseMetadataStatsdb01NsNsIDGetRequest,
        GetNamespaceDatabaseMetadataStatsdb01NsNsIDGetRequestTypedDict,
    )
    from .get_similar_datasets_search_0_2_similar_entry_id_getop import (
        GetSimilarDatasetsSearch02SimilarEntryIDGetRequest,
        GetSimilarDatasetsSearch02SimilarEntryIDGetRequestTypedDict,
    )
    from .get_single_dataset_record_by_entry_id_search_0_1_entry_entry_id_getop import (
        GetSingleDatasetRecordByEntryIDSearch01EntryEntryIDGetRequest,
        GetSingleDatasetRecordByEntryIDSearch01EntryEntryIDGetRequestTypedDict,
    )
    from .get_table_metadata_statsdb_0_1_ns_ns_id_tables_table_id_getop import (
        GetTableMetadataStatsdb01NsNsIDTablesTableIDGetRequest,
        GetTableMetadataStatsdb01NsNsIDTablesTableIDGetRequestTypedDict,
    )
    from .get_timeseries_record_metadata_statsdb_0_1_ns_ns_id_ts_ts_id_getop import (
        GetTimeseriesRecordMetadataStatsdb01NsNsIDTsTsIDGetRequest,
        GetTimeseriesRecordMetadataStatsdb01NsNsIDTsTsIDGetRequestTypedDict,
    )
    from .hit import Hit, HitTypedDict
    from .hits import Hits, HitsTypedDict, TotalUnion, TotalUnionTypedDict
    from .identifier import Identifier, IdentifierTypedDict
    from .indicator import Indicator, IndicatorTypedDict
    from .list_exportable_formats_statsdb_0_1_list_exportable_formats_getop import (
        ListExportableFormatsStatsdb01ListExportableFormatsGetRequest,
        ListExportableFormatsStatsdb01ListExportableFormatsGetRequestTypedDict,
    )
    from .list_facets_search_0_2_list_facets_getop import (
        ListFacetsSearch02ListFacetsGetRequest,
        ListFacetsSearch02ListFacetsGetRequestTypedDict,
    )
    from .list_indicators_statsdb_0_1_ns_ns_id_indicators_getop import (
        ListIndicatorsStatsdb01NsNsIDIndicatorsGetRequest,
        ListIndicatorsStatsdb01NsNsIDIndicatorsGetRequestTypedDict,
    )
    from .list_namespaces_databases_statsdb_0_1_ns_getop import (
        ListNamespacesDatabasesStatsdb01NsGetRequest,
        ListNamespacesDatabasesStatsdb01NsGetRequestTypedDict,
    )
    from .list_tables_statsdb_0_1_ns_ns_id_tables_getop import (
        ListTablesStatsdb01NsNsIDTablesGetRequest,
        ListTablesStatsdb01NsNsIDTablesGetRequestTypedDict,
    )
    from .list_timeseries_statsdb_0_1_ns_ns_id_ts_getop import (
        ListTimeseriesStatsdb01NsNsIDTsGetRequest,
        ListTimeseriesStatsdb01NsNsIDTsGetRequestTypedDict,
    )
    from .location_output import LocationOutput, LocationOutputTypedDict
    from .locationbase import LocationBase, LocationBaseTypedDict
    from .macroregion import MacroRegion, MacroRegionTypedDict
    from .metadatafield import MetadataField, MetadataFieldTypedDict
    from .namespace import Namespace, NamespaceTypedDict
    from .organization_output import OrganizationOutput, OrganizationOutputTypedDict
    from .page_indicator_ import PageIndicator, PageIndicatorTypedDict
    from .page_namespace_ import PageNamespace, PageNamespaceTypedDict
    from .page_tablelistitem_ import PageTableListItem, PageTableListItemTypedDict
    from .page_timeseries_ import PageTimeseries, PageTimeseriesTypedDict
    from .search_data_catalogs_registry_search_catalogs_getop import (
        SearchDataCatalogsRegistrySearchCatalogsGetRequest,
        SearchDataCatalogsRegistrySearchCatalogsGetRequestTypedDict,
    )
    from .search_datasets_search_0_2_query_getop import (
        SearchDatasetsSearch02QueryGetRequest,
        SearchDatasetsSearch02QueryGetRequestTypedDict,
    )
    from .searchindexdatasetrecord import (
        SearchIndexDatasetRecord,
        SearchIndexDatasetRecordID,
        SearchIndexDatasetRecordIDTypedDict,
        SearchIndexDatasetRecordTypedDict,
    )
    from .searchindexentry import SearchIndexEntry, SearchIndexEntryTypedDict
    from .searchindexparty import SearchIndexParty, SearchIndexPartyTypedDict
    from .searchindexresourcerecord import (
        Datasize,
        DatasizeTypedDict,
        SearchIndexResourceRecord,
        SearchIndexResourceRecordID,
        SearchIndexResourceRecordIDTypedDict,
        SearchIndexResourceRecordTypedDict,
    )
    from .searchindexsourcerecord import (
        SearchIndexSourceRecord,
        SearchIndexSourceRecordTypedDict,
    )
    from .searchmeta import SearchMeta, SearchMetaTypedDict
    from .searchqueryresponse import SearchQueryResponse, SearchQueryResponseTypedDict
    from .shards import Shards, ShardsTypedDict
    from .similarhit import SimilarHit, SimilarHitTypedDict
    from .similarhitsresponse import SimilarHitsResponse, SimilarHitsResponseTypedDict
    from .similartotal import SimilarTotal, SimilarTotalTypedDict
    from .software import Software, SoftwareTypedDict
    from .spokenlanguage import SpokenLanguage, SpokenLanguageTypedDict
    from .subregion import SubRegion, SubRegionTypedDict
    from .tablelistitem import TableListItem, TableListItemTypedDict
    from .tablewithschema import TableWithSchema, TableWithSchemaTypedDict
    from .timeseries import Timeseries, TimeseriesTypedDict
    from .timeserieswithschema import (
        TimeseriesWithSchema,
        TimeseriesWithSchemaTypedDict,
    )
    from .topic import Topic, TopicTypedDict
    from .total import Relation, Total, TotalTypedDict
    from .validationerror import (
        Loc,
        LocTypedDict,
        ValidationError,
        ValidationErrorTypedDict,
    )

__all__ = [
    "BodyDatasetSearchUsingElasticDSLSearch02EsSearchPost",
    "BodyDatasetSearchUsingElasticDSLSearch02EsSearchPostTypedDict",
    "Country",
    "CountryTypedDict",
    "DataCatalog",
    "DataCatalogSearchItem",
    "DataCatalogSearchItemTypedDict",
    "DataCatalogSearchResponse",
    "DataCatalogSearchResponseTypedDict",
    "DataCatalogTypedDict",
    "DatasetSearchUsingElasticDSLSearch02EsSearchPostRequest",
    "DatasetSearchUsingElasticDSLSearch02EsSearchPostRequestTypedDict",
    "Datasize",
    "DatasizeTypedDict",
    "DimensionSpec",
    "DimensionSpecTypedDict",
    "Endpoint",
    "EndpointTypedDict",
    "ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetRequest",
    "ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetRequestTypedDict",
    "ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetResponse",
    "ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetResponseResult",
    "ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetResponseResultTypedDict",
    "ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetResponseTypedDict",
    "FacetInfo",
    "FacetInfoTypedDict",
    "FacetItem",
    "FacetItemTypedDict",
    "FacetValuesResponse",
    "FacetValuesResponseTypedDict",
    "FieldSpec",
    "FieldSpecTypedDict",
    "GetDataCatalogRecordRegistryCatalogCatalogIDGetRequest",
    "GetDataCatalogRecordRegistryCatalogCatalogIDGetRequestTypedDict",
    "GetFacetValuesSearch02GetFacetGetRequest",
    "GetFacetValuesSearch02GetFacetGetRequestTypedDict",
    "GetIndicatorMetadataStatsdb01NsNsIDIndicatorsIndIDGetRequest",
    "GetIndicatorMetadataStatsdb01NsNsIDIndicatorsIndIDGetRequestTypedDict",
    "GetNamespaceDatabaseMetadataStatsdb01NsNsIDGetRequest",
    "GetNamespaceDatabaseMetadataStatsdb01NsNsIDGetRequestTypedDict",
    "GetSimilarDatasetsSearch02SimilarEntryIDGetRequest",
    "GetSimilarDatasetsSearch02SimilarEntryIDGetRequestTypedDict",
    "GetSingleDatasetRecordByEntryIDSearch01EntryEntryIDGetRequest",
    "GetSingleDatasetRecordByEntryIDSearch01EntryEntryIDGetRequestTypedDict",
    "GetTableMetadataStatsdb01NsNsIDTablesTableIDGetRequest",
    "GetTableMetadataStatsdb01NsNsIDTablesTableIDGetRequestTypedDict",
    "GetTimeseriesRecordMetadataStatsdb01NsNsIDTsTsIDGetRequest",
    "GetTimeseriesRecordMetadataStatsdb01NsNsIDTsTsIDGetRequestTypedDict",
    "Hit",
    "HitTypedDict",
    "Hits",
    "HitsTypedDict",
    "Identifier",
    "IdentifierTypedDict",
    "Indicator",
    "IndicatorTypedDict",
    "ListExportableFormatsStatsdb01ListExportableFormatsGetRequest",
    "ListExportableFormatsStatsdb01ListExportableFormatsGetRequestTypedDict",
    "ListFacetsSearch02ListFacetsGetRequest",
    "ListFacetsSearch02ListFacetsGetRequestTypedDict",
    "ListIndicatorsStatsdb01NsNsIDIndicatorsGetRequest",
    "ListIndicatorsStatsdb01NsNsIDIndicatorsGetRequestTypedDict",
    "ListNamespacesDatabasesStatsdb01NsGetRequest",
    "ListNamespacesDatabasesStatsdb01NsGetRequestTypedDict",
    "ListTablesStatsdb01NsNsIDTablesGetRequest",
    "ListTablesStatsdb01NsNsIDTablesGetRequestTypedDict",
    "ListTimeseriesStatsdb01NsNsIDTsGetRequest",
    "ListTimeseriesStatsdb01NsNsIDTsGetRequestTypedDict",
    "Loc",
    "LocTypedDict",
    "LocationBase",
    "LocationBaseTypedDict",
    "LocationOutput",
    "LocationOutputTypedDict",
    "MacroRegion",
    "MacroRegionTypedDict",
    "MetadataField",
    "MetadataFieldTypedDict",
    "Namespace",
    "NamespaceTypedDict",
    "OrganizationOutput",
    "OrganizationOutputTypedDict",
    "PageIndicator",
    "PageIndicatorTypedDict",
    "PageNamespace",
    "PageNamespaceTypedDict",
    "PageTableListItem",
    "PageTableListItemTypedDict",
    "PageTimeseries",
    "PageTimeseriesTypedDict",
    "Relation",
    "SearchDataCatalogsRegistrySearchCatalogsGetRequest",
    "SearchDataCatalogsRegistrySearchCatalogsGetRequestTypedDict",
    "SearchDatasetsSearch02QueryGetRequest",
    "SearchDatasetsSearch02QueryGetRequestTypedDict",
    "SearchIndexDatasetRecord",
    "SearchIndexDatasetRecordID",
    "SearchIndexDatasetRecordIDTypedDict",
    "SearchIndexDatasetRecordTypedDict",
    "SearchIndexEntry",
    "SearchIndexEntryTypedDict",
    "SearchIndexParty",
    "SearchIndexPartyTypedDict",
    "SearchIndexResourceRecord",
    "SearchIndexResourceRecordID",
    "SearchIndexResourceRecordIDTypedDict",
    "SearchIndexResourceRecordTypedDict",
    "SearchIndexSourceRecord",
    "SearchIndexSourceRecordTypedDict",
    "SearchMeta",
    "SearchMetaTypedDict",
    "SearchQueryResponse",
    "SearchQueryResponseTypedDict",
    "Shards",
    "ShardsTypedDict",
    "SimilarHit",
    "SimilarHitTypedDict",
    "SimilarHitsResponse",
    "SimilarHitsResponseTypedDict",
    "SimilarTotal",
    "SimilarTotalTypedDict",
    "Software",
    "SoftwareTypedDict",
    "SpokenLanguage",
    "SpokenLanguageTypedDict",
    "SubRegion",
    "SubRegionTypedDict",
    "TableListItem",
    "TableListItemTypedDict",
    "TableWithSchema",
    "TableWithSchemaTypedDict",
    "Timeseries",
    "TimeseriesTypedDict",
    "TimeseriesWithSchema",
    "TimeseriesWithSchemaTypedDict",
    "Topic",
    "TopicTypedDict",
    "Total",
    "TotalTypedDict",
    "TotalUnion",
    "TotalUnionTypedDict",
    "ValidationError",
    "ValidationErrorTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "BodyDatasetSearchUsingElasticDSLSearch02EsSearchPost": ".body_dataset_search_using_elastic_dsl_search_0_2_es_search_post",
    "BodyDatasetSearchUsingElasticDSLSearch02EsSearchPostTypedDict": ".body_dataset_search_using_elastic_dsl_search_0_2_es_search_post",
    "Country": ".country",
    "CountryTypedDict": ".country",
    "DataCatalog": ".datacatalog",
    "DataCatalogTypedDict": ".datacatalog",
    "DataCatalogSearchItem": ".datacatalogsearchitem",
    "DataCatalogSearchItemTypedDict": ".datacatalogsearchitem",
    "DataCatalogSearchResponse": ".datacatalogsearchresponse",
    "DataCatalogSearchResponseTypedDict": ".datacatalogsearchresponse",
    "DatasetSearchUsingElasticDSLSearch02EsSearchPostRequest": ".dataset_search_using_elastic_dsl_search_0_2_es_search_postop",
    "DatasetSearchUsingElasticDSLSearch02EsSearchPostRequestTypedDict": ".dataset_search_using_elastic_dsl_search_0_2_es_search_postop",
    "DimensionSpec": ".dimensionspec",
    "DimensionSpecTypedDict": ".dimensionspec",
    "Endpoint": ".endpoint",
    "EndpointTypedDict": ".endpoint",
    "ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetRequest": ".export_timeseries_data_statsdb_0_1_ns_ns_id_ts_ts_id_export_fileext_getop",
    "ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetRequestTypedDict": ".export_timeseries_data_statsdb_0_1_ns_ns_id_ts_ts_id_export_fileext_getop",
    "ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetResponse": ".export_timeseries_data_statsdb_0_1_ns_ns_id_ts_ts_id_export_fileext_getop",
    "ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetResponseResult": ".export_timeseries_data_statsdb_0_1_ns_ns_id_ts_ts_id_export_fileext_getop",
    "ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetResponseResultTypedDict": ".export_timeseries_data_statsdb_0_1_ns_ns_id_ts_ts_id_export_fileext_getop",
    "ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetResponseTypedDict": ".export_timeseries_data_statsdb_0_1_ns_ns_id_ts_ts_id_export_fileext_getop",
    "FacetInfo": ".facetinfo",
    "FacetInfoTypedDict": ".facetinfo",
    "FacetItem": ".facetitem",
    "FacetItemTypedDict": ".facetitem",
    "FacetValuesResponse": ".facetvaluesresponse",
    "FacetValuesResponseTypedDict": ".facetvaluesresponse",
    "FieldSpec": ".fieldspec",
    "FieldSpecTypedDict": ".fieldspec",
    "GetDataCatalogRecordRegistryCatalogCatalogIDGetRequest": ".get_data_catalog_record_registry_catalog_catalog_id_getop",
    "GetDataCatalogRecordRegistryCatalogCatalogIDGetRequestTypedDict": ".get_data_catalog_record_registry_catalog_catalog_id_getop",
    "GetFacetValuesSearch02GetFacetGetRequest": ".get_facet_values_search_0_2_get_facet_getop",
    "GetFacetValuesSearch02GetFacetGetRequestTypedDict": ".get_facet_values_search_0_2_get_facet_getop",
    "GetIndicatorMetadataStatsdb01NsNsIDIndicatorsIndIDGetRequest": ".get_indicator_metadata_statsdb_0_1_ns_ns_id_indicators_ind_id_getop",
    "GetIndicatorMetadataStatsdb01NsNsIDIndicatorsIndIDGetRequestTypedDict": ".get_indicator_metadata_statsdb_0_1_ns_ns_id_indicators_ind_id_getop",
    "GetNamespaceDatabaseMetadataStatsdb01NsNsIDGetRequest": ".get_namespace_database_metadata_statsdb_0_1_ns_ns_id_getop",
    "GetNamespaceDatabaseMetadataStatsdb01NsNsIDGetRequestTypedDict": ".get_namespace_database_metadata_statsdb_0_1_ns_ns_id_getop",
    "GetSimilarDatasetsSearch02SimilarEntryIDGetRequest": ".get_similar_datasets_search_0_2_similar_entry_id_getop",
    "GetSimilarDatasetsSearch02SimilarEntryIDGetRequestTypedDict": ".get_similar_datasets_search_0_2_similar_entry_id_getop",
    "GetSingleDatasetRecordByEntryIDSearch01EntryEntryIDGetRequest": ".get_single_dataset_record_by_entry_id_search_0_1_entry_entry_id_getop",
    "GetSingleDatasetRecordByEntryIDSearch01EntryEntryIDGetRequestTypedDict": ".get_single_dataset_record_by_entry_id_search_0_1_entry_entry_id_getop",
    "GetTableMetadataStatsdb01NsNsIDTablesTableIDGetRequest": ".get_table_metadata_statsdb_0_1_ns_ns_id_tables_table_id_getop",
    "GetTableMetadataStatsdb01NsNsIDTablesTableIDGetRequestTypedDict": ".get_table_metadata_statsdb_0_1_ns_ns_id_tables_table_id_getop",
    "GetTimeseriesRecordMetadataStatsdb01NsNsIDTsTsIDGetRequest": ".get_timeseries_record_metadata_statsdb_0_1_ns_ns_id_ts_ts_id_getop",
    "GetTimeseriesRecordMetadataStatsdb01NsNsIDTsTsIDGetRequestTypedDict": ".get_timeseries_record_metadata_statsdb_0_1_ns_ns_id_ts_ts_id_getop",
    "Hit": ".hit",
    "HitTypedDict": ".hit",
    "Hits": ".hits",
    "HitsTypedDict": ".hits",
    "TotalUnion": ".hits",
    "TotalUnionTypedDict": ".hits",
    "Identifier": ".identifier",
    "IdentifierTypedDict": ".identifier",
    "Indicator": ".indicator",
    "IndicatorTypedDict": ".indicator",
    "ListExportableFormatsStatsdb01ListExportableFormatsGetRequest": ".list_exportable_formats_statsdb_0_1_list_exportable_formats_getop",
    "ListExportableFormatsStatsdb01ListExportableFormatsGetRequestTypedDict": ".list_exportable_formats_statsdb_0_1_list_exportable_formats_getop",
    "ListFacetsSearch02ListFacetsGetRequest": ".list_facets_search_0_2_list_facets_getop",
    "ListFacetsSearch02ListFacetsGetRequestTypedDict": ".list_facets_search_0_2_list_facets_getop",
    "ListIndicatorsStatsdb01NsNsIDIndicatorsGetRequest": ".list_indicators_statsdb_0_1_ns_ns_id_indicators_getop",
    "ListIndicatorsStatsdb01NsNsIDIndicatorsGetRequestTypedDict": ".list_indicators_statsdb_0_1_ns_ns_id_indicators_getop",
    "ListNamespacesDatabasesStatsdb01NsGetRequest": ".list_namespaces_databases_statsdb_0_1_ns_getop",
    "ListNamespacesDatabasesStatsdb01NsGetRequestTypedDict": ".list_namespaces_databases_statsdb_0_1_ns_getop",
    "ListTablesStatsdb01NsNsIDTablesGetRequest": ".list_tables_statsdb_0_1_ns_ns_id_tables_getop",
    "ListTablesStatsdb01NsNsIDTablesGetRequestTypedDict": ".list_tables_statsdb_0_1_ns_ns_id_tables_getop",
    "ListTimeseriesStatsdb01NsNsIDTsGetRequest": ".list_timeseries_statsdb_0_1_ns_ns_id_ts_getop",
    "ListTimeseriesStatsdb01NsNsIDTsGetRequestTypedDict": ".list_timeseries_statsdb_0_1_ns_ns_id_ts_getop",
    "LocationOutput": ".location_output",
    "LocationOutputTypedDict": ".location_output",
    "LocationBase": ".locationbase",
    "LocationBaseTypedDict": ".locationbase",
    "MacroRegion": ".macroregion",
    "MacroRegionTypedDict": ".macroregion",
    "MetadataField": ".metadatafield",
    "MetadataFieldTypedDict": ".metadatafield",
    "Namespace": ".namespace",
    "NamespaceTypedDict": ".namespace",
    "OrganizationOutput": ".organization_output",
    "OrganizationOutputTypedDict": ".organization_output",
    "PageIndicator": ".page_indicator_",
    "PageIndicatorTypedDict": ".page_indicator_",
    "PageNamespace": ".page_namespace_",
    "PageNamespaceTypedDict": ".page_namespace_",
    "PageTableListItem": ".page_tablelistitem_",
    "PageTableListItemTypedDict": ".page_tablelistitem_",
    "PageTimeseries": ".page_timeseries_",
    "PageTimeseriesTypedDict": ".page_timeseries_",
    "SearchDataCatalogsRegistrySearchCatalogsGetRequest": ".search_data_catalogs_registry_search_catalogs_getop",
    "SearchDataCatalogsRegistrySearchCatalogsGetRequestTypedDict": ".search_data_catalogs_registry_search_catalogs_getop",
    "SearchDatasetsSearch02QueryGetRequest": ".search_datasets_search_0_2_query_getop",
    "SearchDatasetsSearch02QueryGetRequestTypedDict": ".search_datasets_search_0_2_query_getop",
    "SearchIndexDatasetRecord": ".searchindexdatasetrecord",
    "SearchIndexDatasetRecordID": ".searchindexdatasetrecord",
    "SearchIndexDatasetRecordIDTypedDict": ".searchindexdatasetrecord",
    "SearchIndexDatasetRecordTypedDict": ".searchindexdatasetrecord",
    "SearchIndexEntry": ".searchindexentry",
    "SearchIndexEntryTypedDict": ".searchindexentry",
    "SearchIndexParty": ".searchindexparty",
    "SearchIndexPartyTypedDict": ".searchindexparty",
    "Datasize": ".searchindexresourcerecord",
    "DatasizeTypedDict": ".searchindexresourcerecord",
    "SearchIndexResourceRecord": ".searchindexresourcerecord",
    "SearchIndexResourceRecordID": ".searchindexresourcerecord",
    "SearchIndexResourceRecordIDTypedDict": ".searchindexresourcerecord",
    "SearchIndexResourceRecordTypedDict": ".searchindexresourcerecord",
    "SearchIndexSourceRecord": ".searchindexsourcerecord",
    "SearchIndexSourceRecordTypedDict": ".searchindexsourcerecord",
    "SearchMeta": ".searchmeta",
    "SearchMetaTypedDict": ".searchmeta",
    "SearchQueryResponse": ".searchqueryresponse",
    "SearchQueryResponseTypedDict": ".searchqueryresponse",
    "Shards": ".shards",
    "ShardsTypedDict": ".shards",
    "SimilarHit": ".similarhit",
    "SimilarHitTypedDict": ".similarhit",
    "SimilarHitsResponse": ".similarhitsresponse",
    "SimilarHitsResponseTypedDict": ".similarhitsresponse",
    "SimilarTotal": ".similartotal",
    "SimilarTotalTypedDict": ".similartotal",
    "Software": ".software",
    "SoftwareTypedDict": ".software",
    "SpokenLanguage": ".spokenlanguage",
    "SpokenLanguageTypedDict": ".spokenlanguage",
    "SubRegion": ".subregion",
    "SubRegionTypedDict": ".subregion",
    "TableListItem": ".tablelistitem",
    "TableListItemTypedDict": ".tablelistitem",
    "TableWithSchema": ".tablewithschema",
    "TableWithSchemaTypedDict": ".tablewithschema",
    "Timeseries": ".timeseries",
    "TimeseriesTypedDict": ".timeseries",
    "TimeseriesWithSchema": ".timeserieswithschema",
    "TimeseriesWithSchemaTypedDict": ".timeserieswithschema",
    "Topic": ".topic",
    "TopicTypedDict": ".topic",
    "Relation": ".total",
    "Total": ".total",
    "TotalTypedDict": ".total",
    "Loc": ".validationerror",
    "LocTypedDict": ".validationerror",
    "ValidationError": ".validationerror",
    "ValidationErrorTypedDict": ".validationerror",
}


def dynamic_import(modname, retries=3):
    for attempt in range(retries):
        try:
            return import_module(modname, __package__)
        except KeyError:
            # Clear any half-initialized module and retry
            sys.modules.pop(modname, None)
            if attempt == retries - 1:
                break
    raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = dynamic_import(module_name)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = builtins.list(_dynamic_imports.keys())
    return builtins.sorted(lazy_attrs)
