"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import TYPE_CHECKING
from importlib import import_module
import builtins
import sys

if TYPE_CHECKING:
    from .body_search_datasets_dsl import (
        BodySearchDatasetsDsl,
        BodySearchDatasetsDslTypedDict,
    )
    from .country import Country, CountryTypedDict
    from .datacatalog import DataCatalog, DataCatalogTypedDict
    from .datacatalogsearchitem import (
        DataCatalogSearchItem,
        DataCatalogSearchItemTypedDict,
    )
    from .datacatalogsearchresponse import (
        DataCatalogSearchResponse,
        DataCatalogSearchResponseTypedDict,
    )
    from .dimensionspec import DimensionSpec, DimensionSpecTypedDict
    from .endpoint import Endpoint, EndpointTypedDict
    from .export_timeseries_fileop import (
        ExportTimeseriesFileRequest,
        ExportTimeseriesFileRequestTypedDict,
        ExportTimeseriesFileResponse,
        ExportTimeseriesFileResponseResult,
        ExportTimeseriesFileResponseResultTypedDict,
        ExportTimeseriesFileResponseTypedDict,
    )
    from .facetinfo import FacetInfo, FacetInfoTypedDict
    from .facetitem import FacetItem, FacetItemTypedDict
    from .facetvaluesresponse import FacetValuesResponse, FacetValuesResponseTypedDict
    from .fieldspec import FieldSpec, FieldSpecTypedDict
    from .get_catalog_by_idop import (
        GetCatalogByIDRequest,
        GetCatalogByIDRequestTypedDict,
    )
    from .get_dataset_by_entry_idop import (
        GetDatasetByEntryIDRequest,
        GetDatasetByEntryIDRequestTypedDict,
    )
    from .get_namespace_indicatorop import (
        GetNamespaceIndicatorRequest,
        GetNamespaceIndicatorRequestTypedDict,
    )
    from .get_namespace_tableop import (
        GetNamespaceTableRequest,
        GetNamespaceTableRequestTypedDict,
    )
    from .get_namespaceop import GetNamespaceRequest, GetNamespaceRequestTypedDict
    from .get_raw_entry_by_idop import (
        GetRawEntryByIDRequest,
        GetRawEntryByIDRequestTypedDict,
    )
    from .get_search_facet_valuesop import (
        GetSearchFacetValuesRequest,
        GetSearchFacetValuesRequestTypedDict,
    )
    from .get_similar_datasetsop import (
        GetSimilarDatasetsRequest,
        GetSimilarDatasetsRequestTypedDict,
    )
    from .get_timeseriesop import GetTimeseriesRequest, GetTimeseriesRequestTypedDict
    from .hit import Hit, HitTypedDict
    from .hits import Hits, HitsTypedDict, TotalUnion, TotalUnionTypedDict
    from .identifier import Identifier, IdentifierTypedDict
    from .indicator import Indicator, IndicatorTypedDict
    from .list_catalogsop import ListCatalogsRequest, ListCatalogsRequestTypedDict
    from .list_export_formatsop import (
        ListExportFormatsRequest,
        ListExportFormatsRequestTypedDict,
    )
    from .list_indicatorsop import ListIndicatorsRequest, ListIndicatorsRequestTypedDict
    from .list_namespace_tablesop import (
        ListNamespaceTablesRequest,
        ListNamespaceTablesRequestTypedDict,
    )
    from .list_namespacesop import ListNamespacesRequest, ListNamespacesRequestTypedDict
    from .list_search_facetsop import (
        ListSearchFacetsRequest,
        ListSearchFacetsRequestTypedDict,
    )
    from .list_timeseriesop import ListTimeseriesRequest, ListTimeseriesRequestTypedDict
    from .location_output import LocationOutput, LocationOutputTypedDict
    from .locationbase import LocationBase, LocationBaseTypedDict
    from .macroregion import MacroRegion, MacroRegionTypedDict
    from .metadatafield import MetadataField, MetadataFieldTypedDict
    from .namespace import Namespace, NamespaceTypedDict
    from .organization_output import OrganizationOutput, OrganizationOutputTypedDict
    from .page_indicator_ import PageIndicator, PageIndicatorTypedDict
    from .page_namespace_ import PageNamespace, PageNamespaceTypedDict
    from .page_tablelistitem_ import PageTableListItem, PageTableListItemTypedDict
    from .page_timeseries_ import PageTimeseries, PageTimeseriesTypedDict
    from .search_datasets_dslop import (
        SearchDatasetsDslRequest,
        SearchDatasetsDslRequestTypedDict,
    )
    from .search_datasetsop import SearchDatasetsRequest, SearchDatasetsRequestTypedDict
    from .searchindexdatasetrecord import (
        SearchIndexDatasetRecord,
        SearchIndexDatasetRecordID,
        SearchIndexDatasetRecordIDTypedDict,
        SearchIndexDatasetRecordTypedDict,
    )
    from .searchindexentry import SearchIndexEntry, SearchIndexEntryTypedDict
    from .searchindexparty import SearchIndexParty, SearchIndexPartyTypedDict
    from .searchindexresourcerecord import (
        Datasize,
        DatasizeTypedDict,
        SearchIndexResourceRecord,
        SearchIndexResourceRecordID,
        SearchIndexResourceRecordIDTypedDict,
        SearchIndexResourceRecordTypedDict,
    )
    from .searchindexsourcerecord import (
        SearchIndexSourceRecord,
        SearchIndexSourceRecordTypedDict,
    )
    from .searchmeta import SearchMeta, SearchMetaTypedDict
    from .searchqueryresponse import SearchQueryResponse, SearchQueryResponseTypedDict
    from .security import Security, SecurityTypedDict
    from .shards import Shards, ShardsTypedDict
    from .similarhit import SimilarHit, SimilarHitTypedDict
    from .similarhitsresponse import SimilarHitsResponse, SimilarHitsResponseTypedDict
    from .similartotal import SimilarTotal, SimilarTotalTypedDict
    from .software import Software, SoftwareTypedDict
    from .spokenlanguage import SpokenLanguage, SpokenLanguageTypedDict
    from .subregion import SubRegion, SubRegionTypedDict
    from .tablelistitem import TableListItem, TableListItemTypedDict
    from .tablewithschema import TableWithSchema, TableWithSchemaTypedDict
    from .timeseries import Timeseries, TimeseriesTypedDict
    from .timeserieswithschema import (
        TimeseriesWithSchema,
        TimeseriesWithSchemaTypedDict,
    )
    from .topic import Topic, TopicTypedDict
    from .total import Relation, Total, TotalTypedDict
    from .validationerror import (
        Loc,
        LocTypedDict,
        ValidationError,
        ValidationErrorTypedDict,
    )

__all__ = [
    "BodySearchDatasetsDsl",
    "BodySearchDatasetsDslTypedDict",
    "Country",
    "CountryTypedDict",
    "DataCatalog",
    "DataCatalogSearchItem",
    "DataCatalogSearchItemTypedDict",
    "DataCatalogSearchResponse",
    "DataCatalogSearchResponseTypedDict",
    "DataCatalogTypedDict",
    "Datasize",
    "DatasizeTypedDict",
    "DimensionSpec",
    "DimensionSpecTypedDict",
    "Endpoint",
    "EndpointTypedDict",
    "ExportTimeseriesFileRequest",
    "ExportTimeseriesFileRequestTypedDict",
    "ExportTimeseriesFileResponse",
    "ExportTimeseriesFileResponseResult",
    "ExportTimeseriesFileResponseResultTypedDict",
    "ExportTimeseriesFileResponseTypedDict",
    "FacetInfo",
    "FacetInfoTypedDict",
    "FacetItem",
    "FacetItemTypedDict",
    "FacetValuesResponse",
    "FacetValuesResponseTypedDict",
    "FieldSpec",
    "FieldSpecTypedDict",
    "GetCatalogByIDRequest",
    "GetCatalogByIDRequestTypedDict",
    "GetDatasetByEntryIDRequest",
    "GetDatasetByEntryIDRequestTypedDict",
    "GetNamespaceIndicatorRequest",
    "GetNamespaceIndicatorRequestTypedDict",
    "GetNamespaceRequest",
    "GetNamespaceRequestTypedDict",
    "GetNamespaceTableRequest",
    "GetNamespaceTableRequestTypedDict",
    "GetRawEntryByIDRequest",
    "GetRawEntryByIDRequestTypedDict",
    "GetSearchFacetValuesRequest",
    "GetSearchFacetValuesRequestTypedDict",
    "GetSimilarDatasetsRequest",
    "GetSimilarDatasetsRequestTypedDict",
    "GetTimeseriesRequest",
    "GetTimeseriesRequestTypedDict",
    "Hit",
    "HitTypedDict",
    "Hits",
    "HitsTypedDict",
    "Identifier",
    "IdentifierTypedDict",
    "Indicator",
    "IndicatorTypedDict",
    "ListCatalogsRequest",
    "ListCatalogsRequestTypedDict",
    "ListExportFormatsRequest",
    "ListExportFormatsRequestTypedDict",
    "ListIndicatorsRequest",
    "ListIndicatorsRequestTypedDict",
    "ListNamespaceTablesRequest",
    "ListNamespaceTablesRequestTypedDict",
    "ListNamespacesRequest",
    "ListNamespacesRequestTypedDict",
    "ListSearchFacetsRequest",
    "ListSearchFacetsRequestTypedDict",
    "ListTimeseriesRequest",
    "ListTimeseriesRequestTypedDict",
    "Loc",
    "LocTypedDict",
    "LocationBase",
    "LocationBaseTypedDict",
    "LocationOutput",
    "LocationOutputTypedDict",
    "MacroRegion",
    "MacroRegionTypedDict",
    "MetadataField",
    "MetadataFieldTypedDict",
    "Namespace",
    "NamespaceTypedDict",
    "OrganizationOutput",
    "OrganizationOutputTypedDict",
    "PageIndicator",
    "PageIndicatorTypedDict",
    "PageNamespace",
    "PageNamespaceTypedDict",
    "PageTableListItem",
    "PageTableListItemTypedDict",
    "PageTimeseries",
    "PageTimeseriesTypedDict",
    "Relation",
    "SearchDatasetsDslRequest",
    "SearchDatasetsDslRequestTypedDict",
    "SearchDatasetsRequest",
    "SearchDatasetsRequestTypedDict",
    "SearchIndexDatasetRecord",
    "SearchIndexDatasetRecordID",
    "SearchIndexDatasetRecordIDTypedDict",
    "SearchIndexDatasetRecordTypedDict",
    "SearchIndexEntry",
    "SearchIndexEntryTypedDict",
    "SearchIndexParty",
    "SearchIndexPartyTypedDict",
    "SearchIndexResourceRecord",
    "SearchIndexResourceRecordID",
    "SearchIndexResourceRecordIDTypedDict",
    "SearchIndexResourceRecordTypedDict",
    "SearchIndexSourceRecord",
    "SearchIndexSourceRecordTypedDict",
    "SearchMeta",
    "SearchMetaTypedDict",
    "SearchQueryResponse",
    "SearchQueryResponseTypedDict",
    "Security",
    "SecurityTypedDict",
    "Shards",
    "ShardsTypedDict",
    "SimilarHit",
    "SimilarHitTypedDict",
    "SimilarHitsResponse",
    "SimilarHitsResponseTypedDict",
    "SimilarTotal",
    "SimilarTotalTypedDict",
    "Software",
    "SoftwareTypedDict",
    "SpokenLanguage",
    "SpokenLanguageTypedDict",
    "SubRegion",
    "SubRegionTypedDict",
    "TableListItem",
    "TableListItemTypedDict",
    "TableWithSchema",
    "TableWithSchemaTypedDict",
    "Timeseries",
    "TimeseriesTypedDict",
    "TimeseriesWithSchema",
    "TimeseriesWithSchemaTypedDict",
    "Topic",
    "TopicTypedDict",
    "Total",
    "TotalTypedDict",
    "TotalUnion",
    "TotalUnionTypedDict",
    "ValidationError",
    "ValidationErrorTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "BodySearchDatasetsDsl": ".body_search_datasets_dsl",
    "BodySearchDatasetsDslTypedDict": ".body_search_datasets_dsl",
    "Country": ".country",
    "CountryTypedDict": ".country",
    "DataCatalog": ".datacatalog",
    "DataCatalogTypedDict": ".datacatalog",
    "DataCatalogSearchItem": ".datacatalogsearchitem",
    "DataCatalogSearchItemTypedDict": ".datacatalogsearchitem",
    "DataCatalogSearchResponse": ".datacatalogsearchresponse",
    "DataCatalogSearchResponseTypedDict": ".datacatalogsearchresponse",
    "DimensionSpec": ".dimensionspec",
    "DimensionSpecTypedDict": ".dimensionspec",
    "Endpoint": ".endpoint",
    "EndpointTypedDict": ".endpoint",
    "ExportTimeseriesFileRequest": ".export_timeseries_fileop",
    "ExportTimeseriesFileRequestTypedDict": ".export_timeseries_fileop",
    "ExportTimeseriesFileResponse": ".export_timeseries_fileop",
    "ExportTimeseriesFileResponseResult": ".export_timeseries_fileop",
    "ExportTimeseriesFileResponseResultTypedDict": ".export_timeseries_fileop",
    "ExportTimeseriesFileResponseTypedDict": ".export_timeseries_fileop",
    "FacetInfo": ".facetinfo",
    "FacetInfoTypedDict": ".facetinfo",
    "FacetItem": ".facetitem",
    "FacetItemTypedDict": ".facetitem",
    "FacetValuesResponse": ".facetvaluesresponse",
    "FacetValuesResponseTypedDict": ".facetvaluesresponse",
    "FieldSpec": ".fieldspec",
    "FieldSpecTypedDict": ".fieldspec",
    "GetCatalogByIDRequest": ".get_catalog_by_idop",
    "GetCatalogByIDRequestTypedDict": ".get_catalog_by_idop",
    "GetDatasetByEntryIDRequest": ".get_dataset_by_entry_idop",
    "GetDatasetByEntryIDRequestTypedDict": ".get_dataset_by_entry_idop",
    "GetNamespaceIndicatorRequest": ".get_namespace_indicatorop",
    "GetNamespaceIndicatorRequestTypedDict": ".get_namespace_indicatorop",
    "GetNamespaceTableRequest": ".get_namespace_tableop",
    "GetNamespaceTableRequestTypedDict": ".get_namespace_tableop",
    "GetNamespaceRequest": ".get_namespaceop",
    "GetNamespaceRequestTypedDict": ".get_namespaceop",
    "GetRawEntryByIDRequest": ".get_raw_entry_by_idop",
    "GetRawEntryByIDRequestTypedDict": ".get_raw_entry_by_idop",
    "GetSearchFacetValuesRequest": ".get_search_facet_valuesop",
    "GetSearchFacetValuesRequestTypedDict": ".get_search_facet_valuesop",
    "GetSimilarDatasetsRequest": ".get_similar_datasetsop",
    "GetSimilarDatasetsRequestTypedDict": ".get_similar_datasetsop",
    "GetTimeseriesRequest": ".get_timeseriesop",
    "GetTimeseriesRequestTypedDict": ".get_timeseriesop",
    "Hit": ".hit",
    "HitTypedDict": ".hit",
    "Hits": ".hits",
    "HitsTypedDict": ".hits",
    "TotalUnion": ".hits",
    "TotalUnionTypedDict": ".hits",
    "Identifier": ".identifier",
    "IdentifierTypedDict": ".identifier",
    "Indicator": ".indicator",
    "IndicatorTypedDict": ".indicator",
    "ListCatalogsRequest": ".list_catalogsop",
    "ListCatalogsRequestTypedDict": ".list_catalogsop",
    "ListExportFormatsRequest": ".list_export_formatsop",
    "ListExportFormatsRequestTypedDict": ".list_export_formatsop",
    "ListIndicatorsRequest": ".list_indicatorsop",
    "ListIndicatorsRequestTypedDict": ".list_indicatorsop",
    "ListNamespaceTablesRequest": ".list_namespace_tablesop",
    "ListNamespaceTablesRequestTypedDict": ".list_namespace_tablesop",
    "ListNamespacesRequest": ".list_namespacesop",
    "ListNamespacesRequestTypedDict": ".list_namespacesop",
    "ListSearchFacetsRequest": ".list_search_facetsop",
    "ListSearchFacetsRequestTypedDict": ".list_search_facetsop",
    "ListTimeseriesRequest": ".list_timeseriesop",
    "ListTimeseriesRequestTypedDict": ".list_timeseriesop",
    "LocationOutput": ".location_output",
    "LocationOutputTypedDict": ".location_output",
    "LocationBase": ".locationbase",
    "LocationBaseTypedDict": ".locationbase",
    "MacroRegion": ".macroregion",
    "MacroRegionTypedDict": ".macroregion",
    "MetadataField": ".metadatafield",
    "MetadataFieldTypedDict": ".metadatafield",
    "Namespace": ".namespace",
    "NamespaceTypedDict": ".namespace",
    "OrganizationOutput": ".organization_output",
    "OrganizationOutputTypedDict": ".organization_output",
    "PageIndicator": ".page_indicator_",
    "PageIndicatorTypedDict": ".page_indicator_",
    "PageNamespace": ".page_namespace_",
    "PageNamespaceTypedDict": ".page_namespace_",
    "PageTableListItem": ".page_tablelistitem_",
    "PageTableListItemTypedDict": ".page_tablelistitem_",
    "PageTimeseries": ".page_timeseries_",
    "PageTimeseriesTypedDict": ".page_timeseries_",
    "SearchDatasetsDslRequest": ".search_datasets_dslop",
    "SearchDatasetsDslRequestTypedDict": ".search_datasets_dslop",
    "SearchDatasetsRequest": ".search_datasetsop",
    "SearchDatasetsRequestTypedDict": ".search_datasetsop",
    "SearchIndexDatasetRecord": ".searchindexdatasetrecord",
    "SearchIndexDatasetRecordID": ".searchindexdatasetrecord",
    "SearchIndexDatasetRecordIDTypedDict": ".searchindexdatasetrecord",
    "SearchIndexDatasetRecordTypedDict": ".searchindexdatasetrecord",
    "SearchIndexEntry": ".searchindexentry",
    "SearchIndexEntryTypedDict": ".searchindexentry",
    "SearchIndexParty": ".searchindexparty",
    "SearchIndexPartyTypedDict": ".searchindexparty",
    "Datasize": ".searchindexresourcerecord",
    "DatasizeTypedDict": ".searchindexresourcerecord",
    "SearchIndexResourceRecord": ".searchindexresourcerecord",
    "SearchIndexResourceRecordID": ".searchindexresourcerecord",
    "SearchIndexResourceRecordIDTypedDict": ".searchindexresourcerecord",
    "SearchIndexResourceRecordTypedDict": ".searchindexresourcerecord",
    "SearchIndexSourceRecord": ".searchindexsourcerecord",
    "SearchIndexSourceRecordTypedDict": ".searchindexsourcerecord",
    "SearchMeta": ".searchmeta",
    "SearchMetaTypedDict": ".searchmeta",
    "SearchQueryResponse": ".searchqueryresponse",
    "SearchQueryResponseTypedDict": ".searchqueryresponse",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "Shards": ".shards",
    "ShardsTypedDict": ".shards",
    "SimilarHit": ".similarhit",
    "SimilarHitTypedDict": ".similarhit",
    "SimilarHitsResponse": ".similarhitsresponse",
    "SimilarHitsResponseTypedDict": ".similarhitsresponse",
    "SimilarTotal": ".similartotal",
    "SimilarTotalTypedDict": ".similartotal",
    "Software": ".software",
    "SoftwareTypedDict": ".software",
    "SpokenLanguage": ".spokenlanguage",
    "SpokenLanguageTypedDict": ".spokenlanguage",
    "SubRegion": ".subregion",
    "SubRegionTypedDict": ".subregion",
    "TableListItem": ".tablelistitem",
    "TableListItemTypedDict": ".tablelistitem",
    "TableWithSchema": ".tablewithschema",
    "TableWithSchemaTypedDict": ".tablewithschema",
    "Timeseries": ".timeseries",
    "TimeseriesTypedDict": ".timeseries",
    "TimeseriesWithSchema": ".timeserieswithschema",
    "TimeseriesWithSchemaTypedDict": ".timeserieswithschema",
    "Topic": ".topic",
    "TopicTypedDict": ".topic",
    "Relation": ".total",
    "Total": ".total",
    "TotalTypedDict": ".total",
    "Loc": ".validationerror",
    "LocTypedDict": ".validationerror",
    "ValidationError": ".validationerror",
    "ValidationErrorTypedDict": ".validationerror",
}


def dynamic_import(modname, retries=3):
    for attempt in range(retries):
        try:
            return import_module(modname, __package__)
        except KeyError:
            # Clear any half-initialized module and retry
            sys.modules.pop(modname, None)
            if attempt == retries - 1:
                break
    raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = dynamic_import(module_name)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = builtins.list(_dynamic_imports.keys())
    return builtins.sorted(lazy_attrs)
