"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dateno.types import BaseModel
from typing_extensions import TypedDict


class CountryTypedDict(TypedDict):
    r"""Country code and name from ISO 3166-1"""

    id: str
    name: str


class Country(BaseModel):
    r"""Country code and name from ISO 3166-1"""

    id: str

    name: str
