"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dateno.types import BaseModel
from typing_extensions import TypedDict


class DataCatalogSearchItemTypedDict(TypedDict):
    r"""A single catalog entry in catalog search responses."""

    uid: str
    name: str
    link: str


class DataCatalogSearchItem(BaseModel):
    r"""A single catalog entry in catalog search responses."""

    uid: str

    name: str

    link: str
