"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .endpoint import Endpoint, EndpointTypedDict
from .identifier import Identifier, IdentifierTypedDict
from .location_output import LocationOutput, LocationOutputTypedDict
from .organization_output import OrganizationOutput, OrganizationOutputTypedDict
from .software import Software, SoftwareTypedDict
from .spokenlanguage import SpokenLanguage, SpokenLanguageTypedDict
from .topic import Topic, TopicTypedDict
from dateno.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class DataCatalogTypedDict(TypedDict):
    id: str
    uid: str
    name: str
    link: str
    catalog_type: str
    api_status: str
    owner: OrganizationOutputTypedDict
    software: SoftwareTypedDict
    status: str
    properties: NotRequired[Nullable[Dict[str, Any]]]
    api: NotRequired[bool]
    access_mode: NotRequired[List[str]]
    langs: NotRequired[List[SpokenLanguageTypedDict]]
    tags: NotRequired[List[str]]
    content_types: NotRequired[List[str]]
    coverage: NotRequired[List[LocationOutputTypedDict]]
    endpoints: NotRequired[List[EndpointTypedDict]]
    identifiers: NotRequired[List[IdentifierTypedDict]]
    topics: NotRequired[List[TopicTypedDict]]


class DataCatalog(BaseModel):
    id: str

    uid: str

    name: str

    link: str

    catalog_type: str

    api_status: str

    owner: OrganizationOutput

    software: Software

    status: str

    properties: OptionalNullable[Dict[str, Any]] = UNSET

    api: Optional[bool] = False

    access_mode: Optional[List[str]] = None

    langs: Optional[List[SpokenLanguage]] = None

    tags: Optional[List[str]] = None

    content_types: Optional[List[str]] = None

    coverage: Optional[List[LocationOutput]] = None

    endpoints: Optional[List[Endpoint]] = None

    identifiers: Optional[List[Identifier]] = None

    topics: Optional[List[Topic]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "properties",
            "api",
            "access_mode",
            "langs",
            "tags",
            "content_types",
            "coverage",
            "endpoints",
            "identifiers",
            "topics",
        ]
        nullable_fields = ["properties"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
