"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dateno.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class DimensionSpecTypedDict(TypedDict):
    id: str
    name: NotRequired[str]


class DimensionSpec(BaseModel):
    id: str

    name: Optional[str] = None
