"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dateno.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from dateno.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import httpx
from pydantic import model_serializer
from typing import Dict, List, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetRequestTypedDict(
    TypedDict
):
    ns_id: str
    ts_id: str
    r"""Timeseries identifier to retrieve"""
    fileext: str
    r"""Data export extension (e.g. csv, xlsx, json). Unsupported values return 400."""
    apikey: NotRequired[Nullable[str]]


class ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetRequest(BaseModel):
    ns_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    ts_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Timeseries identifier to retrieve"""

    fileext: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Data export extension (e.g. csv, xlsx, json). Unsupported values return 400."""

    apikey: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["apikey"]
        nullable_fields = ["apikey"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetResponseResultTypedDict = TypeAliasType(
    "ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetResponseResultTypedDict",
    Union[httpx.Response, httpx.Response, httpx.Response, httpx.Response],
)


ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetResponseResult = TypeAliasType(
    "ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetResponseResult",
    Union[httpx.Response, httpx.Response, httpx.Response, httpx.Response],
)


class ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetResponseTypedDict(
    TypedDict
):
    headers: Dict[str, List[str]]
    result: (
        ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetResponseResultTypedDict
    )


class ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: ExportTimeseriesDataStatsdb01NsNsIDTsTsIDExportFileextGetResponseResult
