"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dateno.types import BaseModel
from typing_extensions import TypedDict


class FacetItemTypedDict(TypedDict):
    r"""Single bucket from Elastic 'terms' aggregation."""

    key: str
    r"""Facet value"""
    num: int
    r"""Number of documents for the value"""


class FacetItem(BaseModel):
    r"""Single bucket from Elastic 'terms' aggregation."""

    key: str
    r"""Facet value"""

    num: int
    r"""Number of documents for the value"""
