"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .facetitem import FacetItem, FacetItemTypedDict
from dateno.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class FacetValuesResponseTypedDict(TypedDict):
    r"""Facet values and counts for a given facet key."""

    facet_key: str
    r"""Facet field key"""
    items: NotRequired[List[FacetItemTypedDict]]
    r"""Aggregated facet buckets"""


class FacetValuesResponse(BaseModel):
    r"""Facet values and counts for a given facet key."""

    facet_key: str
    r"""Facet field key"""

    items: Optional[List[FacetItem]] = None
    r"""Aggregated facet buckets"""
