"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dateno.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class FieldSpecTypedDict(TypedDict):
    name: str
    ftype: str
    is_array: NotRequired[bool]
    is_dim: NotRequired[bool]
    semtype: NotRequired[str]
    description: NotRequired[str]


class FieldSpec(BaseModel):
    name: str

    ftype: str

    is_array: Optional[bool] = False

    is_dim: Optional[bool] = False

    semtype: Optional[str] = None

    description: Optional[str] = None
