"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from dateno.types import BaseModel
import pydantic
from pydantic import ConfigDict
from typing import Any, Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class HitTypedDict(TypedDict):
    r"""A single hit entry."""

    id: str
    source: Dict[str, Any]
    index: NotRequired[Optional[str]]
    score: NotRequired[Optional[float]]


class Hit(BaseModel):
    r"""A single hit entry."""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    id: Annotated[
        str,
        pydantic.Field(validation_alias="_id", serialization_alias="_id"),
    ]

    source: Annotated[
        Dict[str, Any],
        pydantic.Field(validation_alias="_source", serialization_alias="_source"),
    ]

    index: Annotated[
        Optional[str],
        pydantic.Field(
            default=None,
            validation_alias="_index",
            serialization_alias="_index",
        ),
    ]

    score: Annotated[
        Optional[float],
        pydantic.Field(
            default=None,
            validation_alias="_score",
            serialization_alias="_score",
        ),
    ]

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]
