"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from .hit import Hit, HitTypedDict
from .total import Total, TotalTypedDict
from dateno.types import BaseModel
import pydantic
from pydantic import ConfigDict
from typing import Any, Dict, List, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


TotalUnionTypedDict = TypeAliasType(
    "TotalUnionTypedDict", Union[TotalTypedDict, int, Dict[str, Any]]
)

TotalUnion = TypeAliasType("TotalUnion", Union[Total, int, Dict[str, Any]])


class HitsTypedDict(TypedDict):
    r"""The `hits` section with total, optional max_score, and the list of hits."""

    total: TotalUnionTypedDict
    hits: List[HitTypedDict]
    max_score: NotRequired[Optional[float]]


class Hits(BaseModel):
    r"""The `hits` section with total, optional max_score, and the list of hits."""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    total: TotalUnion

    hits: List[Hit]

    max_score: Optional[float] = None

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]