"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from .metadatafield import MetadataField, MetadataFieldTypedDict
from dateno.types import BaseModel
from pydantic import model_validator
from typing import Any, List, Optional
from typing_extensions import NotRequired, TypedDict


class IndicatorTypedDict(TypedDict):
    id: str
    table: str
    name: str
    metadata: NotRequired[List[MetadataFieldTypedDict]]


class Indicator(BaseModel):
    id: str
    table: str
    name: str
    metadata: Optional[List[MetadataField]] = None

    @model_validator(mode="before")
    @classmethod
    def _coerce_metadata_dict_to_list(cls, data: Any) -> Any:
        """
        Backward/compat: metadata may come as object/dict from backend.
        Keep strong typing (List[MetadataField]) and convert dict -> list[MetadataField].
        """
        if not isinstance(data, dict):
            return data

        md = data.get("metadata", None)
        if md is None or isinstance(md, list):
            return data

        if isinstance(md, dict):
            field_names = list(getattr(MetadataField, "model_fields", {}).keys())

            def _make_item(k: str, v: Any) -> MetadataField:
                if "key" in field_names and "value" in field_names:
                    payload = {"key": k, "value": v}
                elif "name" in field_names and "value" in field_names:
                    payload = {"name": k, "value": v}
                elif "id" in field_names and "value" in field_names:
                    payload = {"id": k, "value": v}
                else:
                    payload = {}
                    if len(field_names) >= 1:
                        payload[field_names[0]] = k
                    if len(field_names) >= 2:
                        payload[field_names[1]] = v
                    else:
                        payload = {"value": {k: v}}
                return MetadataField.model_validate(payload)

            data = dict(data)
            data["metadata"] = [_make_item(str(k), v) for k, v in md.items()]
            return data

        return data
