"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .locationbase import LocationBase, LocationBaseTypedDict
from dateno.types import BaseModel
from typing_extensions import TypedDict


class LocationOutputTypedDict(TypedDict):
    location: LocationBaseTypedDict


class LocationOutput(BaseModel):
    location: LocationBase
