"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .timeseries import Timeseries, TimeseriesTypedDict
from dateno.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class PageTimeseriesTypedDict(TypedDict):
    totals: int
    start: int
    limit: int
    items: List[TimeseriesTypedDict]


class PageTimeseries(BaseModel):
    totals: int

    start: int

    limit: int

    items: List[Timeseries]
