"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .tablelistitem import TableListItem, TableListItemTypedDict
from dateno.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class PageTableListItemTypedDict(TypedDict):
    totals: int
    start: int
    limit: int
    items: List[TableListItemTypedDict]


class PageTableListItem(BaseModel):
    totals: int

    start: int

    limit: int

    items: List[TableListItem]
