"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .indicator import Indicator, IndicatorTypedDict
from dateno.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class PageIndicatorTypedDict(TypedDict):
    totals: int
    start: int
    limit: int
    items: NotRequired[List[IndicatorTypedDict]]


class PageIndicator(BaseModel):
    totals: int

    start: int

    limit: int

    items: Optional[List[Indicator]] = None
