"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .tablelistitem import TableListItem, TableListItemTypedDict
from dateno.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class PageTableListItemTypedDict(TypedDict):
    totals: int
    start: int
    limit: int
    items: NotRequired[List[TableListItemTypedDict]]


class PageTableListItem(BaseModel):
    totals: int

    start: int

    limit: int

    items: Optional[List[TableListItem]] = None
