"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .namespace import Namespace, NamespaceTypedDict
from dateno.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class PageNamespaceTypedDict(TypedDict):
    totals: int
    start: int
    limit: int
    items: List[NamespaceTypedDict]


class PageNamespace(BaseModel):
    totals: int

    start: int

    limit: int

    items: List[Namespace]
