"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .searchindexparty import SearchIndexParty, SearchIndexPartyTypedDict
from dateno.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


SearchIndexDatasetRecordIDTypedDict = TypeAliasType(
    "SearchIndexDatasetRecordIDTypedDict", Union[str, int]
)


SearchIndexDatasetRecordID = TypeAliasType(
    "SearchIndexDatasetRecordID", Union[str, int]
)


class SearchIndexDatasetRecordTypedDict(TypedDict):
    id: SearchIndexDatasetRecordIDTypedDict
    title: NotRequired[Nullable[str]]
    num_resources: NotRequired[Nullable[int]]
    url: NotRequired[Nullable[str]]
    short_text: NotRequired[Nullable[str]]
    description: NotRequired[Nullable[str]]
    has_archive: NotRequired[Nullable[bool]]
    r"""Is there a direct archive download link of the dataset?"""
    tags: NotRequired[Nullable[List[str]]]
    formats: NotRequired[Nullable[List[str]]]
    datatypes: NotRequired[Nullable[List[str]]]
    topics_original: NotRequired[Nullable[List[str]]]
    responsible: NotRequired[List[SearchIndexPartyTypedDict]]
    license_id: NotRequired[Nullable[str]]
    license_name: NotRequired[Nullable[str]]
    license_url: NotRequired[Nullable[str]]


class SearchIndexDatasetRecord(BaseModel):
    id: SearchIndexDatasetRecordID

    title: OptionalNullable[str] = UNSET

    num_resources: OptionalNullable[int] = UNSET

    url: OptionalNullable[str] = UNSET

    short_text: OptionalNullable[str] = UNSET

    description: OptionalNullable[str] = UNSET

    has_archive: OptionalNullable[bool] = UNSET
    r"""Is there a direct archive download link of the dataset?"""

    tags: OptionalNullable[List[str]] = UNSET

    formats: OptionalNullable[List[str]] = UNSET

    datatypes: OptionalNullable[List[str]] = UNSET

    topics_original: OptionalNullable[List[str]] = UNSET

    responsible: Optional[List[SearchIndexParty]] = None

    license_id: OptionalNullable[str] = UNSET

    license_name: OptionalNullable[str] = UNSET

    license_url: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "title",
            "num_resources",
            "url",
            "short_text",
            "description",
            "has_archive",
            "tags",
            "formats",
            "datatypes",
            "topics_original",
            "responsible",
            "license_id",
            "license_name",
            "license_url",
        ]
        nullable_fields = [
            "title",
            "num_resources",
            "url",
            "short_text",
            "description",
            "has_archive",
            "tags",
            "formats",
            "datatypes",
            "topics_original",
            "license_id",
            "license_name",
            "license_url",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
