"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .country import Country, CountryTypedDict
from .macroregion import MacroRegion, MacroRegionTypedDict
from .software import Software, SoftwareTypedDict
from .spokenlanguage import SpokenLanguage, SpokenLanguageTypedDict
from .subregion import SubRegion, SubRegionTypedDict
from dateno.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class SearchIndexSourceRecordTypedDict(TypedDict):
    uid: str
    name: str
    url: str
    catalog_type: str
    owner_name: str
    owner_type: str
    software: SoftwareTypedDict
    langs: NotRequired[List[SpokenLanguageTypedDict]]
    countries: NotRequired[List[CountryTypedDict]]
    macroregions: NotRequired[List[MacroRegionTypedDict]]
    subregions: NotRequired[List[SubRegionTypedDict]]


class SearchIndexSourceRecord(BaseModel):
    uid: str

    name: str

    url: str

    catalog_type: str

    owner_name: str

    owner_type: str

    software: Software

    langs: Optional[List[SpokenLanguage]] = None

    countries: Optional[List[Country]] = None

    macroregions: Optional[List[MacroRegion]] = None

    subregions: Optional[List[SubRegion]] = None
