"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .hits import Hits, HitsTypedDict
from .shards import Shards, ShardsTypedDict
from dateno.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import ConfigDict, model_serializer
from typing import Any, Dict
from typing_extensions import Annotated, NotRequired, TypedDict


class SearchQueryResponseTypedDict(TypedDict):
    r"""Typed view of an Elasticsearch `_search` response.

    What this model guarantees:
    - Accepts both `aggregations` and `aggs` (via `AliasChoices`).
    - Normalizes `hits.total` when ES returns a bare integer.
    - Keeps ES-native field names through aliases and allows unknown fields to pass (`extra=\"allow\"`).
    - Applies light, non-destructive normalization to each hit's `_source`:
    * Ensures `_source.int_id` falls back to `_source.dataset.int_id` if missing.
    * Ensures `_source.resources` is always a list (empty if missing/null).
    * If `_source.dataset.num_resources` is missing, sets it to `len(_source.resources)`.
    * Unifies `source` / `sources`:
    - Preserves all sources in `_source.sources` (list).
    - Picks a primary one into `_source.source` (first with `is_primary=true`, otherwise the first).
    - Cleans each source's `subregions` by dropping items where both `id` and `name` are `null`.
    """

    hits: HitsTypedDict
    r"""The `hits` section with total, optional max_score, and the list of hits."""
    took: NotRequired[Nullable[int]]
    timed_out: NotRequired[Nullable[bool]]
    shards: NotRequired[Nullable[ShardsTypedDict]]
    aggregations: NotRequired[Nullable[Dict[str, Any]]]


class SearchQueryResponse(BaseModel):
    r"""Typed view of an Elasticsearch `_search` response.

    What this model guarantees:
    - Accepts both `aggregations` and `aggs` (via `AliasChoices`).
    - Normalizes `hits.total` when ES returns a bare integer.
    - Keeps ES-native field names through aliases and allows unknown fields to pass (`extra=\"allow\"`).
    - Applies light, non-destructive normalization to each hit's `_source`:
    * Ensures `_source.int_id` falls back to `_source.dataset.int_id` if missing.
    * Ensures `_source.resources` is always a list (empty if missing/null).
    * If `_source.dataset.num_resources` is missing, sets it to `len(_source.resources)`.
    * Unifies `source` / `sources`:
    - Preserves all sources in `_source.sources` (list).
    - Picks a primary one into `_source.source` (first with `is_primary=true`, otherwise the first).
    - Cleans each source's `subregions` by dropping items where both `id` and `name` are `null`.
    """

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    hits: Hits
    r"""The `hits` section with total, optional max_score, and the list of hits."""

    took: OptionalNullable[int] = UNSET

    timed_out: OptionalNullable[bool] = UNSET

    shards: Annotated[OptionalNullable[Shards], pydantic.Field(alias="_shards")] = UNSET

    aggregations: OptionalNullable[Dict[str, Any]] = UNSET

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["took", "timed_out", "_shards", "aggregations"]
        nullable_fields = ["took", "timed_out", "_shards", "aggregations"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        for k, v in serialized.items():
            m[k] = v

        return m
