"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dateno.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from dateno.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SearchDatasetsRequestTypedDict(TypedDict):
    q: NotRequired[str]
    r"""Free-text search query, e.g. 'Atlantic salmon'"""
    filters: NotRequired[List[str]]
    r"""List of filters formatted as `\"field\"=\"value\"` (quotes optional). Example: `\"source.catalog_type\"=\"Geoportal\"`"""
    limit: NotRequired[int]
    offset: NotRequired[int]
    facets: NotRequired[bool]
    r"""If true, response includes aggregations/facets"""
    sort_by: NotRequired[str]
    r"""Comma-separated fields for sorting. Example: `_score` or `scores.feature_score`"""
    apikey: NotRequired[Nullable[str]]


class SearchDatasetsRequest(BaseModel):
    q: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = ""
    r"""Free-text search query, e.g. 'Atlantic salmon'"""

    filters: Annotated[
        Optional[List[str]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""List of filters formatted as `\"field\"=\"value\"` (quotes optional). Example: `\"source.catalog_type\"=\"Geoportal\"`"""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 20

    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 0

    facets: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = True
    r"""If true, response includes aggregations/facets"""

    sort_by: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = "_score"
    r"""Comma-separated fields for sorting. Example: `_score` or `scores.feature_score`"""

    apikey: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "q",
            "filters",
            "limit",
            "offset",
            "facets",
            "sort_by",
            "apikey",
        ]
        nullable_fields = ["apikey"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
