"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dateno.types import BaseModel
from typing_extensions import TypedDict


class SearchMetaTypedDict(TypedDict):
    r"""Pagination metadata for list/search endpoints."""

    offset: int
    limit: int
    num: int
    total: int


class SearchMeta(BaseModel):
    r"""Pagination metadata for list/search endpoints."""

    offset: int

    limit: int

    num: int

    total: int
