"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from dateno.types import BaseModel
import pydantic
from typing import Any, Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SimilarHitTypedDict(TypedDict):
    r"""Single ES hit for similarity search."""
    index: str
    id: str
    source: Dict[str, Any]
    score: NotRequired[Optional[float]]


class SimilarHit(BaseModel):
    r"""Single ES hit for similarity search."""

    index: Annotated[
        str,
        pydantic.Field(validation_alias="_index", serialization_alias="_index"),
    ]

    id: Annotated[
        str,
        pydantic.Field(validation_alias="_id", serialization_alias="_id"),
    ]

    source: Annotated[
        Dict[str, Any],
        pydantic.Field(validation_alias="_source", serialization_alias="_source"),
    ]
    r"""Document source (resources field removed for payload size)"""

    score: Annotated[
        Optional[float],
        pydantic.Field(
            default=None,
            validation_alias="_score",
            serialization_alias="_score",
        ),
    ]
    r"""Relevance score from Elasticsearch"""
