"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from .similarhit import SimilarHit, SimilarHitTypedDict
from .similartotal import SimilarTotal, SimilarTotalTypedDict
from pydantic import Field
from dateno.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class SimilarHitsResponseTypedDict(TypedDict):
    r"""Only the 'hits' section from ES response (legacy behavior)."""

    total: SimilarTotalTypedDict
    max_score: NotRequired[Optional[float]]
    hits: NotRequired[List[SimilarHitTypedDict]]


class SimilarHitsResponse(BaseModel):
    r"""Only the 'hits' section from ES response (legacy behavior)."""

    total: SimilarTotal
    max_score: Optional[float] = None
    hits: List[SimilarHit] = Field(default_factory=list)
