"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dateno.types import BaseModel
from typing_extensions import TypedDict


class SoftwareTypedDict(TypedDict):
    id: str
    name: str


class Software(BaseModel):
    id: str

    name: str
