"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dateno.types import BaseModel
from typing_extensions import TypedDict


class SpokenLanguageTypedDict(TypedDict):
    id: str
    name: str


class SpokenLanguage(BaseModel):
    id: str

    name: str
