"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dimensionspec import DimensionSpec, DimensionSpecTypedDict
from .fieldspec import FieldSpec, FieldSpecTypedDict
from .metadatafield import MetadataField, MetadataFieldTypedDict
from dateno.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TableWithSchemaTypedDict(TypedDict):
    r"""Extended table spec with schema details."""

    id: str
    name: str
    num_rows: int
    ind_key: str
    fields: NotRequired[Nullable[List[FieldSpecTypedDict]]]
    ttype: NotRequired[str]
    dimensions: NotRequired[Nullable[List[DimensionSpecTypedDict]]]
    metadata: NotRequired[Nullable[List[MetadataFieldTypedDict]]]
    schema_: NotRequired[Nullable[List[FieldSpecTypedDict]]]
    r"""Detailed table schema"""


class TableWithSchema(BaseModel):
    r"""Extended table spec with schema details."""

    id: str

    name: str

    num_rows: int

    ind_key: str

    fields: OptionalNullable[List[FieldSpec]] = UNSET

    ttype: Optional[str] = "data"

    dimensions: OptionalNullable[List[DimensionSpec]] = UNSET

    metadata: OptionalNullable[List[MetadataField]] = UNSET

    schema_: Annotated[
        OptionalNullable[List[FieldSpec]], pydantic.Field(alias="schema")
    ] = UNSET
    r"""Detailed table schema"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["fields", "ttype", "dimensions", "metadata", "schema"]
        nullable_fields = ["fields", "dimensions", "metadata", "schema"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
