"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dimensionspec import DimensionSpec, DimensionSpecTypedDict
from .fieldspec import FieldSpec, FieldSpecTypedDict
from .metadatafield import MetadataField, MetadataFieldTypedDict
from dateno.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TableWithSchemaTypedDict(TypedDict):
    r"""Extended table spec with schema details."""

    id: str
    name: str
    num_rows: int
    ind_key: str
    fields: NotRequired[List[FieldSpecTypedDict]]
    ttype: NotRequired[str]
    dimensions: NotRequired[List[DimensionSpecTypedDict]]
    metadata: NotRequired[List[MetadataFieldTypedDict]]
    schema_: NotRequired[List[FieldSpecTypedDict]]
    r"""Detailed table schema"""


class TableWithSchema(BaseModel):
    r"""Extended table spec with schema details."""

    id: str

    name: str

    num_rows: int

    ind_key: str

    fields: Optional[List[FieldSpec]] = None

    ttype: Optional[str] = "data"

    dimensions: Optional[List[DimensionSpec]] = None

    metadata: Optional[List[MetadataField]] = None

    schema_: Annotated[Optional[List[FieldSpec]], pydantic.Field(alias="schema")] = None
    r"""Detailed table schema"""
