"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .metadatafield import MetadataField, MetadataFieldTypedDict
from dateno.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class TimeseriesTypedDict(TypedDict):
    id: str
    indicator: str
    table: str
    name: str
    metadata: NotRequired[List[MetadataFieldTypedDict]]


class Timeseries(BaseModel):
    id: str

    indicator: str

    table: str

    name: str

    metadata: Optional[List[MetadataField]] = None
