"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .fieldspec import FieldSpec, FieldSpecTypedDict
from .metadatafield import MetadataField, MetadataFieldTypedDict
from dateno.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List
from typing_extensions import Annotated, NotRequired, TypedDict


class TimeseriesWithSchemaTypedDict(TypedDict):
    r"""Timeseries metadata with schema (and optional metadata)."""

    id: str
    indicator: str
    table: str
    name: str
    metadata: NotRequired[Nullable[List[MetadataFieldTypedDict]]]
    schema_: NotRequired[Nullable[List[FieldSpecTypedDict]]]
    r"""Schema for the underlying table"""


class TimeseriesWithSchema(BaseModel):
    r"""Timeseries metadata with schema (and optional metadata)."""

    id: str

    indicator: str

    table: str

    name: str

    metadata: OptionalNullable[List[MetadataField]] = UNSET

    schema_: Annotated[
        OptionalNullable[List[FieldSpec]], pydantic.Field(alias="schema")
    ] = UNSET
    r"""Schema for the underlying table"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["metadata", "schema"]
        nullable_fields = ["metadata", "schema"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
