"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dateno.types import BaseModel
import pydantic
from pydantic import ConfigDict
from typing import Any, Dict, Literal
from typing_extensions import TypedDict


Relation = Literal[
    "eq",
    "gte",
]


class TotalTypedDict(TypedDict):
    r"""Modern ES `hits.total` object containing count and relation."""

    value: int
    relation: Relation


class Total(BaseModel):
    r"""Modern ES `hits.total` object containing count and relation."""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    value: int

    relation: Relation

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]
